[package]
name = "skittle-bot-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "skittle_bot_core"
crate-type=["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
env_logger = "0.10.0"
libloading = "0.8.0"
log = "0.4.19"
serde = { version = "1.0.171", features = ["derive"] }
shellwords = "1.1.0"
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.6"

[dependencies.serenity]
version = "0.11.6"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]
