use std::collections::HashMap;
use futures::future::BoxFuture;
use color_eyre::Result;
use serenity::{
    model::prelude::{
        *,
        automod::{
            ActionExecution,
            Rule
        },
        command::CommandPermission
    },
    client::bridge::gateway::event::ShardStageUpdateEvent,
    json::Value, http::ratelimiting::RatelimitInfo, prelude::Context
};

pub type SkittleModuleCommandFn      = fn(ctx: Context, msg: Message, args: Vec<String>) -> BoxFuture<'static, Result<()>>;
pub type SkittleModuleEventManagerFn = fn(ctx: Context, event: EventType)                -> BoxFuture<'static, Result<()>>;

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)]
#[allow(dead_code)]
#[allow(clippy::large_enum_variant)]
pub enum EventType {
    application_command_permissions_update(CommandPermission),
    auto_moderation_rule_create(Rule),
    auto_moderation_rule_update(Rule),
    auto_moderation_rule_delete(Rule),
    auto_moderation_action_execution(ActionExecution),
    cache_ready(Vec<GuildId>),
    channel_create(GuildChannel),
    category_create(ChannelCategory),
    category_delete(ChannelCategory),
    channel_delete(GuildChannel),
    channel_pins_update(ChannelPinsUpdateEvent),
    channel_update(Channel),
    guild_ban_addition(User),
    guild_ban_removal(User),
    guild_create(bool),
    guild_delete(Option<Guild>),
    guild_emojis_update(HashMap<EmojiId, Emoji>),
    guild_integrations_update(GuildId),
    guild_member_addition(Member),
    guild_member_removal(Option<Member>),
    guild_member_update(Member),
    guild_members_chunk(GuildMembersChunkEvent),
    guild_role_create(Role),
    guild_role_delete(Option<Role>),
    guild_role_update(Role),
    guild_stickers_update(HashMap<StickerId, Sticker>),
    guild_unavailable(GuildId),
    guild_update(PartialGuild),
    invite_create(InviteCreateEvent),
    invite_delete(InviteDeleteEvent),
    message(Message),
    message_delete(Option<GuildId>),
    message_delete_bulk(Option<GuildId>),
    message_update(MessageUpdateEvent),
    reaction_add(Reaction),
    reaction_remove(Reaction),
    reaction_remove_all(MessageId),
    presence_replace(Vec<Presence>),
    presence_update(Presence),
    ready(Ready),
    resume(ResumedEvent),
    shard_stage_update(ShardStageUpdateEvent),
    typing_start(TypingStartEvent),
    unknown(Value),
    user_update(CurrentUser),
    voice_server_update(VoiceServerUpdateEvent),
    voice_state_update(VoiceState),
    webhook_update(ChannelId),
    interaction_create(Interaction),
    integration_create(Integration),
    integration_update(Integration),
    integration_delete(Option<ApplicationId>),
    stage_instance_create(StageInstance),
    stage_instance_update(StageInstance),
    stage_instance_delete(StageInstance),
    thread_create(GuildChannel),
    thread_update(GuildChannel),
    thread_delete(PartialGuildChannel),
    thread_list_sync(ThreadListSyncEvent),
    thread_member_update(ThreadMember),
    thread_members_update(ThreadMembersUpdateEvent),
    guild_scheduled_event_create(ScheduledEvent),
    guild_scheduled_event_update(ScheduledEvent),
    guild_scheduled_event_delete(ScheduledEvent),
    guild_scheduled_event_user_add(GuildScheduledEventUserAddEvent),
    guild_scheduled_event_user_remove(GuildScheduledEventUserRemoveEvent),
    ratelimit(RatelimitInfo),
}


impl ToString for EventType {
    fn to_string(&self) -> String {
        match self  {
            Self::application_command_permissions_update(_) => "application_command_permissions_update",
            Self::auto_moderation_rule_create(_) => "auto_moderation_rule_create",
            Self::auto_moderation_rule_update(_) => "auto_moderation_rule_update",
            Self::auto_moderation_rule_delete(_) => "auto_moderation_rule_delete",
            Self::auto_moderation_action_execution(_) => "auto_moderation_action_execution",
            Self::cache_ready(_) => "cache_ready",
            Self::channel_create(_) => "channel_create",
            Self::category_create(_) => "category_create",
            Self::category_delete(_) => "category_delete",
            Self::channel_delete(_) => "channel_delete",
            Self::channel_pins_update(_) => "channel_pins_update",
            Self::channel_update(_) => "channel_update",
            Self::guild_ban_addition(_) => "guild_ban_addition",
            Self::guild_ban_removal(_) => "guild_ban_removal",
            Self::guild_create(_) => "guild_create",
            Self::guild_delete(_) => "guild_delete",
            Self::guild_emojis_update(_) => "guild_emojis_update",
            Self::guild_integrations_update(_) => "guild_integrations_update",
            Self::guild_member_addition(_) => "guild_member_addition",
            Self::guild_member_removal(_) => "guild_member_removal",
            Self::guild_member_update(_) => "guild_member_update",
            Self::guild_members_chunk(_) => "guild_members_chunk",
            Self::guild_role_create(_) => "guild_role_create",
            Self::guild_role_delete(_) => "guild_role_delete",
            Self::guild_role_update(_) => "guild_role_update",
            Self::guild_stickers_update(_) => "guild_stickers_update",
            Self::guild_unavailable(_) => "guild_unavailable",
            Self::guild_update(_) => "guild_update",
            Self::invite_create(_) => "invite_create",
            Self::invite_delete(_) => "invite_delete",
            Self::message(_) => "message",
            Self::message_delete(_) => "message_delete",
            Self::message_delete_bulk(_) => "message_delete_bulk",
            Self::message_update(_) => "message_update",
            Self::reaction_add(_) => "reaction_add",
            Self::reaction_remove(_) => "reaction_remove",
            Self::reaction_remove_all(_) => "reaction_remove_all",
            Self::presence_replace(_) => "presence_replace",
            Self::presence_update(_) => "presence_update",
            Self::ready(_) => "ready",
            Self::resume(_) => "resume",
            Self::shard_stage_update(_) => "shard_stage_update",
            Self::typing_start(_) => "typing_start",
            Self::unknown(_) => "unknown",
            Self::user_update(_) => "user_update",
            Self::voice_server_update(_) => "voice_server_update",
            Self::voice_state_update(_) => "voice_state_update",
            Self::webhook_update(_) => "webhook_update",
            Self::interaction_create(_) => "interaction_create",
            Self::integration_create(_) => "integration_create",
            Self::integration_update(_) => "integration_update",
            Self::integration_delete(_) => "integration_delete",
            Self::stage_instance_create(_) => "stage_instance_create",
            Self::stage_instance_update(_) => "stage_instance_update",
            Self::stage_instance_delete(_) => "stage_instance_delete",
            Self::thread_create(_) => "thread_create",
            Self::thread_update(_) => "thread_update",
            Self::thread_delete(_) => "thread_delete",
            Self::thread_list_sync(_) => "thread_list_sync",
            Self::thread_member_update(_) => "thread_member_update",
            Self::thread_members_update(_) => "thread_members_update",
            Self::guild_scheduled_event_create(_) => "guild_scheduled_event_create",
            Self::guild_scheduled_event_update(_) => "guild_scheduled_event_update",
            Self::guild_scheduled_event_delete(_) => "guild_scheduled_event_delete",
            Self::guild_scheduled_event_user_add(_) => "guild_scheduled_event_user_add",
            Self::guild_scheduled_event_user_remove(_) => "guild_scheduled_event_user_remove",
            Self::ratelimit(_) => "ratelimit",
        }.to_string()
    }
}