prefix=":3"

debug=false
write_logs_to_file = false
db_path="./db"

[secrets]

token=""
client_id=""
client_token=""
invite=""

[roles]
administrator=[]
moderator=[]

[users]
developers=["290545409481244672"]

[modules]
disabled_modules=[] 