prefix=":3"
token="MTEzMDkxMjU5NDQ5MjkyODE0NA.GSsFlB.TLRSF5R28Xz_rO7kt-rcCW0pfaMrBJBJ-ABVl0"
client_id="1130912594492928144"
client_secret="nu0BJlY1Q7lEwn-VQd2I_PluD2aksWaf"
invite="https://discord.com/api/oauth2/authorize?client_id=1130912594492928144&permissions=8&scope=bot"